sudo: false
language: node_js
node_js: stable
cache: npm
branches:
  only:
    - source
install:
  - npm install hexo
script:
  - hexo clean
  - hexo g
deploy:
  provider: pages
  skip-cleanup: false
  github-token: $GH_TOKEN
  keep-history: false
  on:
    branch: master
  local-dir: public