sudo: false
language: node_js
node_js: stable
cache: npm
branches:
  only:
    - source
script:
  - hexo clean
  - hexo g
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on: master
  local-dir: public