sudo: false
language: node_js
node_js: stable
cache: npm
branches:
  only:
    - source
script:
  - npm install hexo
  - hexo clean
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "nomadli"
  - git config user.email "dzym79@qq.com"
  - git add .
  - git commit -a -m "Auto update docs by Travis CI."
  - git push --force --quiet "https://${GH_TOKEN}@github.com/nomadli79/nomadli79.github.io.git" master:master
deploy:
  provider: pages
  skip-cleanup: false
  github-token: $GH_TOKEN
  keep-history: false
  on: master
  local-dir: public